TEST:
  EVAL_TASK: detection
  DURING_TRAINING: True
DATASETS:
  TRAIN_DATASETNAME_SUFFIX: '_vision_query'
  USE_OVERRIDE_CATEGORY: True
  USE_CAPTION_PROMPT: True
  FEW_SHOT: 5
  USE_OVERRIDE_CATEGORY: True
  SHUFFLE_SEED: 3
  DISABLE_SHUFFLE: True
  SPECIAL_SAFEGUARD_FOR_COCO_GROUNDING: False
DATALOADER:
  DISTRIBUTE_CHUNK_AMONG_NODE: False
VISION_QUERY:
  MAX_QUERY_NUMBER: 5
  VISION_SCALE: 1.0
  PURE_TEXT_RATE: 0.
  TEXT_DROPOUT: 0.
  NUM_QUERY_PER_CLASS: 5
  QUERY_BANK_PATH: ""
  RANDOM_KSHOT: False
  NUM_TURNS: 3
  OFFLINE_WITH_ONLINE: True
SOLVER:
  WEIGHT_DECAY: 0.05
  GATE_LR: 0.0001
  TEST_WITH_INFERENCE: True
  USE_AUTOSTEP: True
  SEED: 10
  STEP_PATIENCE: 3
  CHECKPOINT_PER_EPOCH: 1.0
  AUTO_TERMINATE_PATIENCE: 10
  MODEL_EMA: 0.0
  TUNING_HIGHLEVEL_OVERRIDE: full
  MAX_TO_KEEP: 2
MODEL:
  BACKBONE:
    FREEZE_CONV_BODY_AT: 2
GROUNDINGDINO:
  box_threshold: 0.08
