DATALOADER:
  ASPECT_RATIO_GROUPING: false
  SIZE_DIVISIBILITY: 32
DATASETS:
  GENERAL_COPY: 16
  OVERRIDE_CATEGORY: '[{"id": 1, "name": "fish", "supercategory": "creatures"}, {"id":
    2, "name": "jellyfish", "supercategory": "creatures"}, {"id": 3, "name": "penguin",
    "supercategory": "creatures"}, {"id": 4, "name": "puffin", "supercategory": "creatures"},
    {"id": 5, "name": "shark", "supercategory": "creatures"}, {"id": 6, "name": "starfish",
    "supercategory": "creatures"}, {"id": 7, "name": "stingray", "supercategory":
    "creatures"}]'
  PREDEFINED_TEXT: odinw/pothole/category_description.json
  REGISTER:
    test:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/test/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/test
    train:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_wrong:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/annotations_without_background_wrong_label.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_10_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot10_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_10_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot10_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_10_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot10_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_1_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot1_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_1_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot1_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_1_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot1_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_3_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot3_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_3_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot3_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_3_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot3_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_5_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot5_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_5_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot5_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    train_5_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train/fewshot_train_shot5_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/train
    val:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/annotations_without_background.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_10_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot10_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_10_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot10_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_10_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot10_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_1_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot1_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_1_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot1_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_1_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot1_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_3_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot3_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_3_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot3_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_3_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot3_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_5_3:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot5_seed3.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_5_30:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot5_seed30.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
    val_5_300:
      ann_file: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid/fewshot_val_shot5_seed300.json
      img_dir: odinw/Aquarium/Aquarium Combined.v2-raw-1024.coco/valid
  TEST: ("val",)
  TRAIN: ("train",)
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: 800
MODEL:
  ATSS:
    NUM_CLASSES: 8
  DYHEAD:
    NUM_CLASSES: 8
  FCOS:
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NUM_CLASSES: 8
SOLVER:
  CHECKPOINT_PERIOD: 100
  MAX_EPOCH: 12
  WARMUP_ITERS: 0
TEST:
  IMS_PER_BATCH: 8
VISION_QUERY:
  DATASET_NAME: 'Aquarium'
GROUNDINGDINO:
  box_threshold: 0.08