DATALOADER: {ASPECT_RATIO_GROUPING: false, SIZE_DIVISIBILITY: 32}
DATASETS:
  CAPTION_PROMPT: '[{"prefix": "there is a ", "name": "package", "suffix": " on the
    porch"}]'
  GENERAL_COPY: 16
  OVERRIDE_CATEGORY: '[{"id": 1, "name": "package", "supercategory": "packages"}]'
  PREDEFINED_TEXT: odinw/pothole/category_description.json
  REGISTER:
    test: {ann_file: odinw/Packages/Raw/test/annotations_without_background.json,
      img_dir: odinw/Packages/Raw/test}
    train: {ann_file: odinw/Packages/Raw/train/annotations_without_background.json,
      img_dir: odinw/Packages/Raw/train}
    train_10_3: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot10_seed3.json,
      img_dir: odinw/Packages/Raw/train}
    train_10_30: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot10_seed30.json,
      img_dir: odinw/Packages/Raw/train}
    train_10_300: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot10_seed300.json,
      img_dir: odinw/Packages/Raw/train}
    train_1_3: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot1_seed3.json,
      img_dir: odinw/Packages/Raw/train}
    train_1_30: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot1_seed30.json,
      img_dir: odinw/Packages/Raw/train}
    train_1_300: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot1_seed300.json,
      img_dir: odinw/Packages/Raw/train}
    train_3_3: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot3_seed3.json,
      img_dir: odinw/Packages/Raw/train}
    train_3_30: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot3_seed30.json,
      img_dir: odinw/Packages/Raw/train}
    train_3_300: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot3_seed300.json,
      img_dir: odinw/Packages/Raw/train}
    train_5_3: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot5_seed3.json,
      img_dir: odinw/Packages/Raw/train}
    train_5_30: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot5_seed30.json,
      img_dir: odinw/Packages/Raw/train}
    train_5_300: {ann_file: odinw/Packages/Raw/train/fewshot_train_shot5_seed300.json,
      img_dir: odinw/Packages/Raw/train}
    val: {ann_file: odinw/Packages/Raw/valid/annotations_without_background.json,
      img_dir: odinw/Packages/Raw/valid}
    val_10_3: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot10_seed3.json, img_dir: odinw/Packages/Raw/valid}
    val_10_30: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot10_seed30.json,
      img_dir: odinw/Packages/Raw/valid}
    val_10_300: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot10_seed300.json,
      img_dir: odinw/Packages/Raw/valid}
    val_1_3: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot1_seed3.json, img_dir: odinw/Packages/Raw/valid}
    val_1_30: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot1_seed30.json, img_dir: odinw/Packages/Raw/valid}
    val_1_300: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot1_seed300.json,
      img_dir: odinw/Packages/Raw/valid}
    val_3_3: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot3_seed3.json, img_dir: odinw/Packages/Raw/valid}
    val_3_30: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot3_seed30.json, img_dir: odinw/Packages/Raw/valid}
    val_3_300: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot3_seed300.json,
      img_dir: odinw/Packages/Raw/valid}
    val_5_3: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot5_seed3.json, img_dir: odinw/Packages/Raw/valid}
    val_5_30: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot5_seed30.json, img_dir: odinw/Packages/Raw/valid}
    val_5_300: {ann_file: odinw/Packages/Raw/valid/fewshot_val_shot5_seed300.json,
      img_dir: odinw/Packages/Raw/valid}
  TEST: ("val",)
  TRAIN: ("train",)
INPUT: {MAX_SIZE_TEST: 1333, MAX_SIZE_TRAIN: 1333, MIN_SIZE_TEST: 800, MIN_SIZE_TRAIN: 800}
MODEL:
  ATSS: {NUM_CLASSES: 2}
  DYHEAD: {NUM_CLASSES: 2}
  FCOS: {NUM_CLASSES: 2}
  ROI_BOX_HEAD: {NUM_CLASSES: 2}
SOLVER: {CHECKPOINT_PERIOD: 100, MAX_EPOCH: 12, WARMUP_ITERS: 0}
TEST: {IMS_PER_BATCH: 8}
VISION_QUERY:
  DATASET_NAME: 'Packages'